---
version: "3.7"
services:
  snapserver:
    image: kirintwn/snapserver
    container_name: snapserver
    command: "--stream.stream=spotify:///librespot?name=spotify&username=${SPOTIFY_USERNAME}&password=${SPOTIFY_PASSWORD}"
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    restart: always
